### PR TITLE
i#1569: Fix compilation errors with GCC11 and "-O3" option

### PR DESCRIPTION
**Pull request by philramsey-arm**
GCC11 has stricter requirements for uninitialised
variables in -O3 mode

Issue: #1569

### CODE REVIEW

File: core/arch/arch.c [hunk 1]
```diff
@@ -3893,7 +3893,7 @@ get_time()
 bool
```
Comment (derekbruening) [inline core/arch/arch.c:3893]: nit: Convention is to put a colon after the issue number in the PR title

**Review by derekbruening — APPROVED** [review]

**Comment by philramsey-arm** [comment]
@derekbruening the CI is failing due to #5329. Do you know if anyone is looking into this? Thanks

**Comment by abhinav92003** [comment]
> @derekbruening the CI is failing due to #5329. Do you know if anyone is looking into this? Thanks

Yes, I'm looking into it now.

**Comment by abhinav92003** [comment]
@philramsey-arm Should be fixed now. Please retry.
