### ISSUE TITLE
build broken on older cmake: include directories messed up for extensions

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1056]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on January 15, 2013 16:26:21_

I believe this is due to my issue #1052 multi-config change http://build.chromium.org/p/client.dynamorio/builders/linux-dr-package/builds/85/steps/Package&#37;20DynamoRIO/logs/stdio debug-32: ***\* 50 build errors ****
    /.../dynamorio/ext/drcontainers/drvector.c:35:20: error: dr_api.h: No such file or directory http://build.chromium.org/p/client.dynamorio/builders/linux-dr/builds/134/steps/pre-commit&#37;20suite/logs/stdio [ 79&#37;] /mnt/data/b/build/slave/linux-dr/dynamorio/ext/drmgr/drmgr.c:37:20: ./mnt/data/b/build/slave/linux-dr/dynamorio/ext/drcontainers/hashtable.c:39:20: error: dr_api.h: No such file or directory
error: dr_api.h: No such file or directory
In file included from /mnt/data/b/build/slave/linux-dr/dynamorio/ext/drmgr/drmgr.c:38:
/mnt/data/b/build/slave/linux-dr/dynamorio/ext/drmgr/drmgr.h:98: error: expected declaration specifiers or ‘...’ before ‘*’ token

I can repro with cmake 2.8.0.  It works with 2.8.3+.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1056_
