### ISSUE TITLE
AArch64 prefetch and flush instructions are not marked by drmemtrace

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4328]
drcachesim's tracer is missing AArch64 checks for opcodes in instru_t::instr_to_prefetch_type and instru_t::instr_is_flush.

**Comment by abhinav92003** [comment]
I noticed something odd in how the x86 `clflush` instruction is handled by the tracer. 

It is handled by `instrument_memref`, same as other instructions with memory references. Therefore, the L0 filter is also applied to it. This means that it may be filtered out of the trace. I verified this by adding multiple `clflush` in a pure asm app. 
https://github.com/DynamoRIO/dynamorio/blob/cdc24cb13514cca50012dc9397b446323ddd62c5/clients/drcachesim/tracer/tracer.cpp#L902



Without `-L0_filter` all of them show up:
```
rm -r drmemtrace.*;  ./bin64/drrun -t drcachesim  -offline a.out; ./bin64/drrun -t drcachesim -indir drmemtrace* -simulator_type view
<marker: timestamp 13239920657418705>
<marker: tid 375365 on core 15>
  0x0000000000401000  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
  0x0000000000401008  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
  0x0000000000401010  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
  0x0000000000401018  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
  0x0000000000401020  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
  0x0000000000401028  48 c7 c0 3c 00 00 00 mov    $0x0000003c, %rax
  0x000000000040102f  48 31 ff             xor    %rdi, %rdi
  0x0000000000401032  0f 05                syscall
<marker: timestamp 13239920657418786>
<marker: tid 375365 on core 15>
View tool results:
              8 : total disassembled instructions
```

With `-L0_filter` only one shows up:
```
rm -r drmemtrace.*;  ./bin64/drrun -t drcachesim -L0_filter -L0D_size 0      -offline a.out; ./bin64/drrun -t drcachesim -indir drmemtrace* -simulator_type view
<marker: timestamp 13239920381948985>
<marker: tid 374727 on core 15>
  0x0000000000401000  0f ae 3c 25 34 10 40 clflush 0x00401034
                      00
<marker: timestamp 13239920381949056>
<marker: tid 374727 on core 15>
View tool results:
              1 : total disassembled instructions
```

Is this filtering out of flush instruction intended?

**Comment by abhinav92003** [comment]
As `clflush` may write dirty cache lines to memory, I guess it does make sense to apply the L0 filter to it. But another way to look at it is that the `clflush` should also invalidate the L0 cache line.

**Comment by abhinav92003** [comment]
On a different note than above:
AArch64 flush instructions seem a bit more complicated to handle than x86 `clflush`. 

In flush instructions, like  `dc cvac, <va-to-flush>`, the `va-to-flush` source operand is not considered a memref by `opnd_is_memory_reference`, and therefore isn't handled by `instrument_memref` at all. This differs from the handling of the memory address operand in `clflush`. I'm assuming we want same behaviour for AArch64 as x86, and include a ref to the flushed memory address, right? @derekbruening 

Also, AArch64 flush instructions are actually an alias to the `sys` opcode[1], which is used by various other operations. So any implementation will need to be aware of more than just the AArch64 opcode. 


[1]: https://static.docs.arm.com/ddi0596/a/DDI_0596_ARM_a64_instruction_set_architecture.pdf, page 1250

**Comment by derekbruening** [comment]
> In flush instructions, like dc cvac, <va-to-flush>, the va-to-flush source operand is not considered a memref

That's #4329

**Comment by derekbruening** [comment]
#4341 broke the build on my machine with gcc 9.3.0 (@abhinav92003 -- I would expect you to have the same gcc version?).  I will fix since this is blocking me right now:
```
src/clients/drcachesim/tracer/instru.cpp: In static member function ‘static short unsigned int instru_t::get_aarch64_prefetch_type(ptr_int_t)’:
src/clients/drcachesim/tracer/instru.cpp:115:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
  115 |         switch (target_policy) {
      |         ^~~~~~
src/clients/drcachesim/tracer/instru.cpp:123:5: note: here
  123 |     case 0b01: // prefetch for instruction
      |     ^~~~
src/clients/drcachesim/tracer/instru.cpp:124:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
  124 |         switch (target_policy) {
      |         ^~~~~~
src/clients/drcachesim/tracer/instru.cpp:132:5: note: here
  132 |     case 0b10: // prefetch for store
      |     ^~~~
cc1plus: all warnings being treated as errors
```

**Comment by abhinav92003** [comment]
> #4341 broke the build on my machine with gcc 9.3.0 (@abhinav92003 -- I would expect you to have the same gcc version?).

Indeed, it's the same.
```
gcc (Debian 9.3.0-8) 9.3.0
```

>  I will fix since this is blocking me right now:

Thanks, apologies for the breakage.

**Comment by derekbruening** [comment]
> Indeed, it's the same.

Do you see the same warning when you build on that machine?

**Comment by derekbruening** [comment]
> > Indeed, it's the same.
> 
> Do you see the same warning when you build on that machine?

Actually I do not see the warning in a straight-up build: only in my aarch64-on-x86 build.  And presumably the Travis CI test of that build uses a different compiler.

**Comment by derekbruening** [comment]
> > > Indeed, it's the same.
> > 
> > 
> > Do you see the same warning when you build on that machine?
> 
> Actually I do not see the warning in a straight-up build: only in my aarch64-on-x86 build. And presumably the Travis CI test of that build uses a different compiler.

Right, because it's in aarch64-only code :)

**Comment by abhinav92003** [comment]
> Right, because it's in aarch64-only code :)

Ah yes. On my AArch64, I have an old gcc
`gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`

**Comment by abhinav92003** [comment]
Follow-up work for privileged flush instrs in #4406
