### ISSUE TITLE
Build failure with Clang: unused function 'is_empty_fragment'

### ISSUE THREAD

**Issue by yan12125** [DynamoRIO/dynamorio#1788]
Architecture: x86_64
OS: Arch Linux
Compiler: clang 3.7.0
Steps to reproduce:
```
$ git clone https://github.com/DynamoRIO/dynamorio && cd dynamorio
$ CC=clang CXX=clang++ cmake .
$ make
```
The result:
```
[ 14%] Building C object core/CMakeFiles/dynamorio.dir/link.c.o
/home/yen/tmp/dynamorio/core/link.c:271:1: error: unused function 'is_empty_fragment' [-Werror,-Wunused-function]
is_empty_fragment(fragment_t *f)
^
1 error generated.
core/CMakeFiles/dynamorio.dir/build.make:158: recipe for target 'core/CMakeFiles/dynamorio.dir/link.c.o' failed
make[2]: *** [core/CMakeFiles/dynamorio.dir/link.c.o] Error 1
CMakeFiles/Makefile2:280: recipe for target 'core/CMakeFiles/dynamorio.dir/all' failed
make[1]: *** [core/CMakeFiles/dynamorio.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by derekbruening** [comment]
Our only clang automated tests are for the 32-bit-only limited Mac support for Dr. Memory, so officially we do not support 64-bit clang as there are no regression tests for it.  If you would like to use 64-bit clang we suggest contributing cycles on a machine to run the test suite and ensure the build isn't just broken again later on, though please wait for us to update our CDash test suite instructions.  For now, please see https://github.com/DynamoRIO/dynamorio/wiki/Contributing for how to submit a patch.

**Comment by yan12125** [comment]
Which versions of g++ are officially supported? I've tried to build with g++ 5.2.0 but failed with a more strange error:
```
[ 72%] Building CXX object ext/drgui/CMakeFiles/drgui.dir/drgui_main_window.cpp.o
/home/yen/tmp/dynamorio/ext/drgui/drgui_main_window.cpp: In destructor ‘drgui_main_window_t::~drgui_main_window_t()’:
/home/yen/tmp/dynamorio/ext/drgui/drgui_main_window.cpp:100:1: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
 drgui_main_window_t::~drgui_main_window_t(void)
 ^
cc1plus: all warnings being treated as errors
ext/drgui/CMakeFiles/drgui.dir/build.make:102: recipe for target 'ext/drgui/CMakeFiles/drgui.dir/drgui_main_window.cpp.o' failed
make[2]: *** [ext/drgui/CMakeFiles/drgui.dir/drgui_main_window.cpp.o] Error 1
CMakeFiles/Makefile2:1474: recipe for target 'ext/drgui/CMakeFiles/drgui.dir/all' failed
make[1]: *** [ext/drgui/CMakeFiles/drgui.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by derekbruening** [comment]
Mostly we're using 4.7 and 4.8.  Some of the automated bots may still have 4.4.  I have a new setup with 5.1.1 and I can reproduce the drgui failure you cite.  I will fix it.

**Comment by derekbruening** [comment]
Split off as #1797

**Comment by yan12125** [comment]
Thanks for the work in  #1797. I just want DynamoRIO can build on my machine without errors. This can be closed until you decide to support 64-bit clang on Linux.

**Comment by zhaoqin** [comment]
I just download the clang 3.7 but cannot reproduce the build failure on my Ubuntu 14.04:
```
> Clang/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang --version
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

> CC=/.../Clang/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang CXX=/.../Clang/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ cmake ../../dynamorio.git
...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.clang

> make -j
...
[ 99%] Built target tracedump
[100%] Built target wrap
```

Also, you may want to have build directory separate from the source directory.

**Comment by yan12125** [comment]
I encounter the same error on a newly installed VM with Ubuntu 14.04.3 server. The compiler is downloaded from http://llvm.org/releases/download.html.

**Comment by zhaoqin** [comment]
We just updated the DynamoRIO, please try again.

**Comment by yan12125** [comment]
Thanks for the great work! Building works on Arch Linux with both GCC and Clang.
