### ISSUE TITLE
RISCV build failing in HEAD: "liblz4.so: undefined reference to `XXH32'"

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#6900]
The RISCV build suddenly started failing in PR #6896 and PR #6899: https://github.com/DynamoRIO/dynamorio/actions/workflows/ci-riscv64.yml

I did a run on the master branch and it fails there too in the same way, so it's from some kind of toolchain change on the Github Actions VM image or something:

https://github.com/DynamoRIO/dynamorio/actions/runs/10078155689/job/27862403699
```
riscv64-debug-internal: **** 28 build errors ****
	/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld: /usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/lib/liblz4.so: undefined reference to `XXH32_update'
	/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld: /usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/lib/liblz4.so: undefined reference to `XXH32_digest'
	/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld: /usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/lib/liblz4.so: undefined reference to `XXH32_reset'
	/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld: /usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/lib/liblz4.so: undefined reference to `XXH32'
	collect2: error: ld returned 1 exit status
	make[2]: *** [clients/drcachesim/CMakeFiles/prefetch_analyzer_launcher.dir/build.make:139: clients/bin64/prefetch_analyzer_launcher] Error 1
	make[1]: *** [CMakeFiles/Makefile2:2993: clients/drcachesim/CMakeFiles/prefetch_analyzer_launcher.dir/all] Error 2
```

**Comment by derekbruening** [comment]
@ksco hoping you could take a look?

**Comment by ksco** [comment]
Ack, it seems we are pulling these packages from Debian sid for some reason, it's better to use a stable source. I'll look into it.

**Comment by ksco** [comment]
Fixed above.
