### PR TITLE
i#3792: Remove alias attribute and replace by real function body.

### LINKED ISSUE #3792: New compile warning errors with gcc 8.2
All builds with this version are now failing with

```
FAILED: core/CMakeFiles/drdecode.dir/string.c.o
/usr/bin/cc  -I/usr/local/google/home/hgreving/dynamorio/src/core/drlibc -I/usr/local/google/home/hgreving/dynamorio/src/core/arch/x86 -I/usr/local/google/home/hgreving/dynamorio/src/core/unix -I/usr/local/google/home/hgreving/dynamorio/src/core/arch -I/usr/local/google/home/hgreving/dynamorio/src/core/lib -I. -Iinclude/annotations -m32  -fno-strict-aliasing -fno-stack-protector -mpreferred-stack-boundary=2 -fvisibility=internal  -std=gnu99 -g3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -MD -MT core/CMakeFiles/drdecode.dir/string.c.o -MF core/CMakeFiles/drdecode.dir/string.c.o.d -o core/CMakeFiles/drdecode.dir/string.c.o   -c /usr/local/google/home/hgreving/dynamorio/src/core/string.c                               
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:176:1: error: ‘__memmove_chk’ alias between functions of incompatible types ‘void *(void *, const void *, size_t,  size_t)’ {aka ‘void *(void *, const
void *, unsigned int,  unsigned int)’} and ‘void *(void *, const void *, size_t)’ {aka ‘void *(void *, const void *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __memmove_chk(void *dst, const void *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:155:1: note: aliased declaration here
 d_r_memmove(void *dst, const void *src, size_t n)
 ^~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:200:1: error: ‘__strncat_chk’ alias between functions of incompatible types ‘void *(char *, const char *, size_t,  size_t)’ {aka ‘void *(char *, const
char *, unsigned int,  unsigned int)’} and ‘char *(char *, const char *, size_t)’ {aka ‘char *(char *, const char *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __strncat_chk(char *dst, const char *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:134:1: note: aliased declaration here
 d_r_strncat(char *dest, const char *src, size_t n)
 ^~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:188:1: error: ‘__strncpy_chk’ alias between functions of incompatible types ‘void *(char *, const char *, size_t,  size_t)’ {aka ‘void *(char *, const
char *, unsigned int,  unsigned int)’} and ‘char *(char *, const char *, size_t)’ {aka ‘char *(char *, const char *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __strncpy_chk(char *dst, const char *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:121:1: note: aliased declaration here
 d_r_strncpy(char *dst, const char *src, size_t n)
 ^~~~~~~~~~~
cc1: all warnings being treated as errors
[24/1227] Building C object core/CMakeFiles/dynamorio_static_nohide.dir/fragment.c.o
ninja: build stopped: subcommand failed.

```

```
hgreving@hendrik-desktop:~/dynamorio/build$ gcc --version
gcc (Debian 8.2.0-14+build1) 8.2.0
```

I have not tested whether this affect only the gcc version I am working with or any >= 8.2.

### PR DESCRIPTION
**Pull request by hgreving2304**
GCC >= 8.2 does not accept a different function declaration used for the alias macro
without a warning. Instead of subduing the warning and relying on aliasing it, we now
inline the function body directly with a macro.

Disables the warning errors -Wstringop-truncation, -Wformat-truncation, and
-Wno-stringop-overflow. All 3 warnings are related to '\0' string termination. DynamoRIO
manages string termination and error handling itself in many places. Various re-factoring
would be required in order to turn on the warnings.

Fixes #3792

### CODE REVIEW

**Comment by hgreving2304** [comment]
Hold off with review. There's an error.

**Comment by derekbruening** [comment]
Did not look at anything except the title:

> Replace alias attribute with pre-processor macro.

This sounds like it will not work: we need something at link time.  A pre-processor macro renaming these _chk macros or sthg is not going to be enough.  We need actual symbols.

**Comment by hgreving2304** [comment]
> Did not look at anything except the title:
> 
> > Replace alias attribute with pre-processor macro.
> 
> This sounds like it will not work: we need something at link time. A pre-processor macro renaming these _chk macros or sthg is not going to be enough. We need actual symbols.

Misleading wording then. Look at the patch..

**Comment by derekbruening** [comment]
> i#3792: Remove alias attribute and inline code instead.

This to me also sounds like it will not end up with an actual implementation of each _chk function: the goal is to have a symbol pointing somewhere, not to inlined into the callers and not have a function at all.

File: core/string.c [hunk 1]
```diff
@@ -174,40 +181,19 @@ d_r_memmove(void *dst, const void *src, size_t n)
  */
```
Comment (derekbruening) [inline core/string.c]: Please update the comment which still talks about aliasing.  Explain why we can't alias.

File: CMakeLists.txt [hunk 2]
```diff
@@ -754,6 +754,23 @@ if (UNIX)
     if (nounused_avail)
       set(WARN "${WARN} -Wno-unused-but-set-variable")
     endif (nounused_avail)
+    # XXX i#3793: DynamoRIO manages '\0' termination and error states itself in
```
Comment (derekbruening) [inline CMakeLists.txt]: 3793 is this PR.  What issue do you mean to refer to?

File: core/string.c [hunk 3]
```diff
@@ -117,28 +117,32 @@ d_r_strrchr(const char *str, int c)
 /* Private strncpy.  Standard caveat about not copying trailing null byte on
  * truncation applies.
  */
+#define D_R_STRNCPY_BODY                      \
```
Comment (derekbruening) [inline core/string.c]: style: use parens `()` for anything non-trivial

Comment (derekbruening) [inline core/string.c]: style: Always use do..while around multi-statement macros

File: core/string.c (hunk 1 above)
Comment (hgreving2304) [reply core/string.c]: Missed that, thanks.

File: CMakeLists.txt (hunk 2 above)
Comment (hgreving2304) [reply CMakeLists.txt]: Fixed (i#3792).

File: core/string.c (hunk 3 above)
Comment (hgreving2304) [reply core/string.c]: Done.

Comment (hgreving2304) [reply core/string.c]: Done.

File: CMakeLists.txt (hunk 2 above)
Comment (derekbruening) [reply CMakeLists.txt]: But I see no information on null char termination in #3792?

Comment (hgreving2304) [reply CMakeLists.txt]: The same compiler switch also turned on these warning errors in this patch. I've updated the issue. They are all somewhat related, I don't think we need a separate issue?

Comment (derekbruening) [reply CMakeLists.txt]: Same issue seems ok so long as there is actually some information there.  Otherwise, if I were a future reader and I saw this reference I would think you got the number wrong and I would go searching the tracker looking for an issue about string termation.

Comment (hgreving2304) [reply CMakeLists.txt]: It's described in #3792 now.

File: core/string.c [hunk 4]
```diff
@@ -117,28 +117,36 @@ d_r_strrchr(const char *str, int c)
...
+#define D_R_STRNCPY_BODY()                        \
+    do {                                          \
+        size_t i;                                 \
+        for (i = 0; i < n && src[i] != '\0'; i++) \
+            dst[i] = src[i];                      \
+        /* Pad the rest with nulls. */            \
+        for (; i < n; i++)                        \
+            dst[i] = '\0';                        \
+        return dst;                               \
+    } while (0);
```
Comment (derekbruening) [inline core/string.c]: style: No semicolon here.  Please see all the other macros using do..while (hundreds of them).

File: core/string.c [hunk 5]
```diff
@@ -117,28 +117,36 @@ d_r_strrchr(const char *str, int c)
...
 d_r_strncpy(char *dst, const char *src, size_t n)
 {
-    size_t i;
-    for (i = 0; i < n && src[i] != '\0'; i++)
-        dst[i] = src[i];
-    /* Pad the rest with nulls. */
-    for (; i < n; i++)
-        dst[i] = '\0';
-    return dst;
+    D_R_STRNCPY_BODY()
```
Comment (derekbruening) [inline core/string.c]: style: End in a semicolon here.

Comment (derekbruening) [reply core/string.c]: (This is not just a DR arbitrary style choice: hiding the ; messes up parsers and hinders readability.)

File: core/string.c (hunk 4 above)
Comment (hgreving2304) [reply core/string.c]: I actually did and the first two ones I found have a semicolon :)

core/vmareas.c:LOCK_VECTOR
core/vmareas.c:UNLOCK_VECTOR

Do you want me to fix here since we're at it already?

File: core/string.c (hunk 5 above)
Comment (hgreving2304) [reply core/string.c]: Fixed.

**Comment by hgreving2304** [comment]
run arm tests

File: core/string.c (hunk 4 above)
Comment (derekbruening) [reply core/string.c]: None of them have no semicolon in their instantiations.

Comment (hgreving2304) [reply core/string.c]: You said

> style: No semicolon here

which I think referred to `} while (0);`

LOCK_VECTOR and UNLOCK_VECTOR have a semicolon there. Most others don't.
