### ISSUE TITLE
ninja build fails with short build dir name

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1782]
I think we've seen this before but I wanted to document it:

If I build in d:/derek/dr/git/build_x86_dbg it works just fine:

```
09:45 AM ~/dr/git/build_x86_dbg
% ninja -v drearlyhelp2
[1/2] "C:/PROGRA~2/CMake2~1.8/bin/cmcldeps.exe" RC D:\derek\dr\git\src\core\win32\resources.rc "core/CMakeFiles/drearlyhelp2.dir/win32/resources.rc.res.d" core\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res  "Note: including file: "  "C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe" C:\PROGRA~1\MICROS~4\Windows\v7.1\Bin\RC.Exe  /nologo -ID:/derek/dr/git/src/core/arch/x86 -ID:/derek/dr/git/src/core/win32 -ID:/derek/dr/git/src/core/arch -ID:/derek/dr/git/src/core/lib -ID:/derek/dr/git/build_x86_dbg -ID:/derek/dr/git/build_x86_dbg/include/annotations    -DRC_IS_EARLY2  -Ddrearlyhelp2_EXPORTS /focore\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res D:\derek\dr\git\src\core\win32\resources.rc
[2/2] cmd.exe /c cd . && "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E vs_link_dll C:\PROGRA~2\MICROS~2.0\VC\bin\link.exe /nologo core\CMakeFiles\drearlyhelp2.dir\win32\early_inject_helper2.c.obj core\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res  /out:lib32\drearlyhelp2.dll /implib:lib32\drearlyhelp2.lib /pdb:lib32\drearlyhelp2.pdb /dll /version:0.0 /machine:X86  /subsystem:console,5.00 /debug   /debug /release /opt:ref /machine:I386 /dll /NODEFAULTLIB /base:0x71110000 /entry:DllMain  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd .
   Creating library lib32\drearlyhelp2.lib and object lib32\drearlyhelp2.exp
```

But if I build in d:/derek/dr/git/foo it fails:

```
09:35 AM ~/dr/git/foo
% ninja -v drearlyhelp2 
[1/2] "C:/PROGRA~2/CMake2~1.8/bin/cmcldeps.exe" RC D:\derek\dr\git\src\core\win32\resources.rc "core/CMakeFiles/drearlyhelp2.dir/win32/resources.rc.res.d" core\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res  "Note: including file: "  "C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe" C:\PROGRA~1\MICROS~4\Windows\v7.1\Bin\RC.Exe  /nologo -ID:/derek/dr/git/src/core/arch/x86 -ID:/derek/dr/git/src/core/win32 -ID:/derek/dr/git/src/core/arch -ID:/derek/dr/git/src/core/lib -ID:/derek/dr/git/foo -ID:/derek/dr/git/foo/include/annotations    -DRC_IS_EARLY2  -Ddrearlyhelp2_EXPORTS /focore\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res D:\derek\dr\git\src\core\win32\resources.rc
FAILED: "C:/PROGRA~2/CMake2~1.8/bin/cmcldeps.exe" RC D:\derek\dr\git\src\core\win32\resources.rc "core/CMakeFiles/drearlyhelp2.dir/win32/resources.rc.res.d" core\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res  "Note: including file: "  "C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe" C:\PROGRA~1\MICROS~4\Windows\v7.1\Bin\RC.Exe  /nologo -ID:/derek/dr/git/src/core/arch/x86 -ID:/derek/dr/git/src/core/win32 -ID:/derek/dr/git/src/core/arch -ID:/derek/dr/git/src/core/lib -ID:/derek/dr/git/foo -ID:/derek/dr/git/foo/include/annotations    -DRC_IS_EARLY2  -Ddrearlyhelp2_EXPORTS /focore\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res D:\derek\dr\git\src\core\win32\resources.rc
cl : Command line warning D9002 : ignoring unknown option '/focore\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res.dep.obj'
D:\derek\dr\git\src\core\win32\resources.rc(55) : fatal error C1083: Cannot open include file: 'configure.h': No such file or directory
ninja: build stopped: subcommand failed.
```

The build commands are identical other than the current dir and the -I for
the current dir.

The RC command works, so it's something with cmcldeps or something?

```
09:38 AM ~/dr/git/foo
% C:/PROGRA~1/MICROS~4/Windows/v7.1/Bin/RC.Exe  /nologo -ID:/derek/dr/git/src/core/arch/x86 -ID:/derek/dr/git/src/core/win32 -ID:/derek/dr/git/src/core/arch -ID:/derek/dr/git/src/core/lib -ID:/derek/dr/git/foo -ID:/derek/dr/git/foo/include/annotations    -DRC_IS_EARLY2  -Ddrearlyhelp2_EXPORTS /focore\CMakeFiles\drearlyhelp2.dir\win32\resources.rc.res 'D:\derek\dr\git\src\core\win32\resources.rc'
```

**Comment by derekbruening** [comment]
This works with cmake 3.3.1
