### ISSUE TITLE
New compile warning errors with gcc 8.2

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3792]
All builds with this version are now failing with

```
FAILED: core/CMakeFiles/drdecode.dir/string.c.o
/usr/bin/cc  -I/usr/local/google/home/hgreving/dynamorio/src/core/drlibc -I/usr/local/google/home/hgreving/dynamorio/src/core/arch/x86 -I/usr/local/google/home/hgreving/dynamorio/src/core/unix -I/usr/local/google/home/hgreving/dynamorio/src/core/arch -I/usr/local/google/home/hgreving/dynamorio/src/core/lib -I. -Iinclude/annotations -m32  -fno-strict-aliasing -fno-stack-protector -mpreferred-stack-boundary=2 -fvisibility=internal  -std=gnu99 -g3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -MD -MT core/CMakeFiles/drdecode.dir/string.c.o -MF core/CMakeFiles/drdecode.dir/string.c.o.d -o core/CMakeFiles/drdecode.dir/string.c.o   -c /usr/local/google/home/hgreving/dynamorio/src/core/string.c                               
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:176:1: error: ‘__memmove_chk’ alias between functions of incompatible types ‘void *(void *, const void *, size_t,  size_t)’ {aka ‘void *(void *, const
void *, unsigned int,  unsigned int)’} and ‘void *(void *, const void *, size_t)’ {aka ‘void *(void *, const void *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __memmove_chk(void *dst, const void *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:155:1: note: aliased declaration here
 d_r_memmove(void *dst, const void *src, size_t n)
 ^~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:200:1: error: ‘__strncat_chk’ alias between functions of incompatible types ‘void *(char *, const char *, size_t,  size_t)’ {aka ‘void *(char *, const
char *, unsigned int,  unsigned int)’} and ‘char *(char *, const char *, size_t)’ {aka ‘char *(char *, const char *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __strncat_chk(char *dst, const char *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:134:1: note: aliased declaration here
 d_r_strncat(char *dest, const char *src, size_t n)
 ^~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:188:1: error: ‘__strncpy_chk’ alias between functions of incompatible types ‘void *(char *, const char *, size_t,  size_t)’ {aka ‘void *(char *, const
char *, unsigned int,  unsigned int)’} and ‘char *(char *, const char *, size_t)’ {aka ‘char *(char *, const char *, unsigned int)’} [-Werror=attribute-alias]                                                    
 __strncpy_chk(char *dst, const char *src, size_t n, size_t dst_len)
 ^~~~~~~~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/core/string.c:121:1: note: aliased declaration here
 d_r_strncpy(char *dst, const char *src, size_t n)
 ^~~~~~~~~~~
cc1: all warnings being treated as errors
[24/1227] Building C object core/CMakeFiles/dynamorio_static_nohide.dir/fragment.c.o
ninja: build stopped: subcommand failed.

```

```
hgreving@hendrik-desktop:~/dynamorio/build$ gcc --version
gcc (Debian 8.2.0-14+build1) 8.2.0
```

I have not tested whether this affect only the gcc version I am working with or any >= 8.2.

**Comment by hgreving2304** [comment]
The same compiler switch also turned on warning errors about potential '\0' string termination bugs, caused by the warnings -Wstringop-truncation, -Wformat-truncation, and  -Wstringop-overflow:

```
n file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:42:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c: In function ‘read_options’:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:105:22: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
 #    define _tcsncpy strncpy
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:753:5: note: in expansion of macro ‘_tcsncpy’
     _tcsncpy(tmp, ptr, len);
     ^~~~~~~~
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/share.h:68,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/utils.h:37,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:37:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:101:21: note: length computed here
 #    define _tcslen strlen
/usr/local/google/home/hgreving/dynamorio/src/core/lib/globals_shared.h:432:32: note: in definition of macro ‘MIN’
 #    define MIN(x, y) ((x) <= (y) ? (x) : (y))
                                ^
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:752:42: note: in expansion of macro ‘_tcslen’
     len = MIN(DR_MAX_OPTIONS_LENGTH - 1, _tcslen(ptr));
                                          ^~~~~~~
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:42:
In function ‘add_extra_option.part.2’,
    inlined from ‘add_extra_option’ at /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:265:1,
    inlined from ‘read_options’ at /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:860:17:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:105:22: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
 #    define _tcsncpy strncpy
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:277:9: note: in expansion of macro ‘_tcsncpy’
         _tcsncpy(opt_info->extra_opts[idx], opt, len);
         ^~~~~~~~
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/share.h:68,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/utils.h:37,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:37:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c: In function ‘read_options’:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:101:21: note: length computed here
 #    define _tcslen strlen
/usr/local/google/home/hgreving/dynamorio/src/core/lib/globals_shared.h:432:32: note: in definition of macro ‘MIN’
 #    define MIN(x, y) ((x) <= (y) ? (x) : (y))
                                ^
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:274:46: note: in expansion of macro ‘_tcslen’
         len = MIN(DR_MAX_OPTIONS_LENGTH - 1, _tcslen(opt));
                                              ^~~~~~~
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:42:
In function ‘add_extra_option.part.2’,
    inlined from ‘add_extra_option’ at /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:265:1,
    inlined from ‘add_extra_option_char’ at /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:293:16,
    inlined from ‘dr_register_process’ at /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:1170:5:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:105:22: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
 #    define _tcsncpy strncpy
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:277:9: note: in expansion of macro ‘_tcsncpy’
         _tcsncpy(opt_info->extra_opts[idx], opt, len);
         ^~~~~~~~
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/share.h:68,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/utils.h:37,
                 from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:37:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c: In function ‘dr_register_process’:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:101:21: note: length computed here
 #    define _tcslen strlen
/usr/local/google/home/hgreving/dynamorio/src/core/lib/globals_shared.h:432:32: note: in definition of macro ‘MIN’
 #    define MIN(x, y) ((x) <= (y) ? (x) : (y))
                                ^
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:274:46: note: in expansion of macro ‘_tcslen’
         len = MIN(DR_MAX_OPTIONS_LENGTH - 1, _tcslen(opt));
                                              ^~~~~~~
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c: In function ‘dr_unregister_process’:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:476:39: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
     _snprintf(fname, fname_len, "%s/%s", dir, subdir);
                                       ^
In file included from /usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:42:
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_frontend.h:108:23: note: ‘snprintf’ output between 2 and 513 bytes into a destination of size 512
 #    define _snprintf snprintf
/usr/local/google/home/hgreving/dynamorio/src/libutil/dr_config.c:476:5: note: in expansion of macro ‘_snprintf’
     _snprintf(fname, fname_len, "%s/%s", dir, subdir);

```
