### PR TITLE
i#3917: Fix gcc 9.2.1 build errors

### LINKED ISSUE #3917: build failures with gcc 9.2.1: sigcontext define conflict; drgui override warning
dynamorio does not compile on ubuntu 19.10.  There are mutually incompatible versions of sigcontext.h that are co-included.  It compiles fine for me on ubuntu 18.04 and ubuntu 16.10

```
/mnt/robhenry/dynamorio/dynamorio/core/unix/include/sigcontext.h:20: error: "FP_XSTATE_MAGIC2_SIZE" redefined [-Werror]
   20 | #define FP_XSTATE_MAGIC2_SIZE sizeof(FP_XSTATE_MAGIC2)
      | 
from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/drlibc.c:43:
/usr/include/x86_64-linux-gnu/bits/sigcontext.h:29: note: this is the location of the previous definition
   29 | #define FP_XSTATE_MAGIC2_SIZE sizeof (FP_XSTATE_MAGIC2)
      | 
```
gcc is gcc 9.2.1-9ubuntu2

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a duplicate sigcontext define and adds a missing override in
drgui to address issues building with gcc 9.2.1

Fixes #3917

### CODE REVIEW

**Comment by derekbruening** [comment]
A64 failure is #2892
