### ISSUE TITLE
build failures with gcc 9.2.1: sigcontext define conflict; drgui override warning

### ISSUE THREAD

**Issue by RobertHenry6bev** [DynamoRIO/dynamorio#3917]
dynamorio does not compile on ubuntu 19.10.  There are mutually incompatible versions of sigcontext.h that are co-included.  It compiles fine for me on ubuntu 18.04 and ubuntu 16.10

```
/mnt/robhenry/dynamorio/dynamorio/core/unix/include/sigcontext.h:20: error: "FP_XSTATE_MAGIC2_SIZE" redefined [-Werror]
   20 | #define FP_XSTATE_MAGIC2_SIZE sizeof(FP_XSTATE_MAGIC2)
      | 
from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/drlibc.c:43:
/usr/include/x86_64-linux-gnu/bits/sigcontext.h:29: note: this is the location of the previous definition
   29 | #define FP_XSTATE_MAGIC2_SIZE sizeof (FP_XSTATE_MAGIC2)
      | 
```
gcc is gcc 9.2.1-9ubuntu2

**Comment by derekbruening** [comment]
Is that the full output?  Where is the sigcontext.h from /usr/include coming from?  I thought core/ completely avoided it.  The full compiler error output may show the inclusion path -- could you paste that in.

**Comment by RobertHenry6bev** [comment]
1%] Built target generate_syslog
[  1%] Built target api_headers
[  1%] Building C object core/CMakeFiles/drlibc.dir/drlibc/drlibc.c.o
In file included from /mnt/robhenry/dynamorio/dynamorio/core/unix/os_public.h:46,
                 from /mnt/robhenry/dynamorio/dynamorio/core/unix/os_exports.h:47,
                 from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/../globals.h:348,
                 from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/drlibc.c:43:
/mnt/robhenry/dynamorio/dynamorio/core/unix/include/sigcontext.h:20: error: "FP_XSTATE_MAGIC2_SIZE" redefined [-Werror]
   20 | #define FP_XSTATE_MAGIC2_SIZE sizeof(FP_XSTATE_MAGIC2)
      |
In file included from /usr/include/signal.h:291,
                 from /mnt/robhenry/dynamorio/dynamorio/core/lib/globals_shared.h:125,
                 from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/../globals.h:93,
                 from /mnt/robhenry/dynamorio/dynamorio/core/drlibc/drlibc.c:43:
/usr/include/x86_64-linux-gnu/bits/sigcontext.h:29: note: this is the location of the previous definition
   29 | #define FP_XSTATE_MAGIC2_SIZE sizeof (FP_XSTATE_MAGIC2)
      |
cc1: all warnings being treated as errors
make[2]: *** [core/CMakeFiles/drlibc.dir/build.make:83: core/CMakeFiles/drlibc.dir/drlibc/drlibc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:212: core/CMakeFiles/drlibc.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by Carrotman42** [comment]
Thanks for the info. As indicated from the more verbose failure message, we do indeed `#include <signal.h>` in this environment from globals_shared.h.

If it is just that one constant (and the other two defined nearby) we might be able to add an ifndef guard to DR's version of those constants: I looked them up, and they are defined to be the same (at least, for the file I found online), so we just need to define them if they aren't already defined afaict.

**Comment by derekbruening** [comment]
I have a dev machine with gcc 9.2.1 in FC31 which hits this sigcontext error, and a drgui warning:
```
In file included from dynamorio/ext/drgui/moc_drgui_main_window.cpp:9:
dynamorio/ext/drgui/../../../../src/dynamorio/ext/drgui/drgui_main_window.h:67:5: error: ‘virtual void drgui_main_window_t::closeEvent(QCloseEvent*)’ can be marked override [-Werror=suggest-override]
   67 |     closeEvent(QCloseEvent *event);
      |     ^~~~~~~~~~
```

I will fix these as they are in front of me and blocking me.  I do not plan to test Ubuntu 19.10 -- those using that should send pull requests to fix issues there.
