### ISSUE TITLE
DynamoRIO does not build with GCC 7.2

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2737]
I hit a couple of issues when trying to build DynamoRIO with GCC 7.2 and GNU ld (GNU Binutils) 2.29.1
 on Arch Linux (x86_64). Both issues seem related to linking, but unfortunately I am not sure what the actual issues are:

    /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libc.a(memmove-sse2-unaligned-erms.o): In function `__memmove_sse2_unaligned':
    (.text+0x10): multiple definition of `memcpy'
    ../../lib64/libdrhelper.a(x86_shared.asm.o):(.text+0xa9): first defined here
    collect2: error: ld returned 1 exit status

    /usr/bin/ld: CMakeFiles/client.drmgr-test.dir/client-interface/drmgr-test.c.o: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Nonrepresentable section on output

**Comment by fhahn** [comment]
At least the  `-fPIC ` problem also exists with GCC 6 on X86 #1958

**Comment by derekbruening** [comment]
I'm assuming that 7bb03fe fixed this
